pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: merge
