pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependency-update]

  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: squash
        strict: true

