name: uritemplate4s
baseurl: /uritemplate4s
description: URI template implementation for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: com.gubbns
markdown: kramdown
