version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: node download
          command: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run:
          name: node install
          command: sudo apt-get install -y nodejs
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: build
          command: sbt ";scalafix;test:compile"
      - save_cache:
          paths:
            - ~/.ivy2/cache
            - ~/.sbt
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run:
          name: test
          command: sbt "test"
