version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: gen cache key
          command: find . -type f -name "*.sbt" -exec md5sum "{}" + | sort > /tmp/sbt-hash.txt
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/tmp/sbt-hash.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: build
          command: sbt ";scalafixTest;test:compile"
      - save_cache:
          paths:
            - ~/.ivy2/cache
            - ~/.sbt
            - ~/.cache
          key: v1-dependencies-{{ checksum "/tmp/sbt-hash.txt" }}
      - run:
          name: test
          command: sbt "test"
