addSbtPlugin("com.47deg"  % "sbt-microsites" % "0.7.16")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.8.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.6.0-M5")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.2")
addSbtPlugin("org.portable-scala" % "sbt-crossproject" % "0.4.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.4.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.22")
